export * from './homePackageAdminPage';
export * from './HomePage'
export * from './loginPage';
export * from './registerPage';
export * from './confirmRegisterPage';
export * from './page404';
export * from './page500';
export * from './OrderRegisterationPage';
export * from './resultListPage';